name: Process Images
on: pull_request
jobs:
  build:
    name: sharp
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.fork == false && github.actor != 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-primes-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-primes-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: bun install

      - name: ✧ Process images and Report results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PULL_REQUEST: ${{ toJSON(github.event.pull_request) }}
        run: bun ./scripts/action-process-images.ts
